#!/bin/bash

# Exit silently if the graphics driver is not installed.
[[ ! -f /opt/nvidia/bin/nvidia-settings ]] && exit 0

name="vdpau-va-driver-vp9"
echo "building ${name}"

mkdir -p builddir && cd builddir
rm -fr ${name}

if [[ ! -f ${name}.tar.gz ]]; then
    url="https://github.com/xuanruiqi/${name}.git"
    echo "git clone --depth 1 ${url}"
    git clone --depth 1 ${url}
    tar czf ${name}.tar.gz ${name}
fi

tar xzf ${name}.tar.gz

if [[ -d ${name} ]]; then
    cd ${name}
    # search /opt/nvidia/{lib64,lib} paths
    LDFLAGS="-L/opt/nvidia/lib64 -L/opt/nvidia/lib -L/usr/local/lib" \
        ./autogen.sh --prefix=/usr --enable-glx && \
    make -j 4 && make install && \
    rm -f /usr/lib64/dri/vdpau_drv_video.la
fi

