#!/bin/bash

name="lame-3.100"
echo "building ${name}"

mkdir -p builddir && cd builddir
rm -fr ${name}

if [[ ! -f ${name}.tar.gz ]]; then
    url="https://downloads.sourceforge.net/project/lame/lame/3.100/${name}.tar.gz"
    echo "curl -LO $url"
    curl -LO $url
fi

tar xzf ${name}.tar.gz

if [[ -d ${name} ]]; then
    cores=`grep -c '^cpu[0-9]' /proc/stat`
    cd ${name}
    ./configure --prefix=/usr/local --enable-shared --enable-nasm && \
    make -j ${cores} && make install && \
    rm -f /usr/local/lib/libmp3lame.la /usr/local/lib/libmp3lame.a
fi

