#!/bin/bash

name="xvidcore"
version="1.3.7"
echo "building ${name}-${version}"

mkdir -p builddir && cd builddir
rm -fr ${name}

if [[ ! -f ${name}-${version}.tar.gz ]]; then
    url="https://downloads.xvid.com/downloads/${name}-${version}.tar.gz"
    echo "curl -LO ${url}"
    curl -LO ${url}
fi

tar xzf ${name}-${version}.tar.gz

if [[ -d ${name} ]]; then
    cores=`grep -c '^cpu[0-9]' /proc/stat`
    cd ${name}/build/generic
    ./configure --prefix=/usr/local --disable-static && \
    make -j ${cores} && \
    rm -f /usr/local/lib/libxvidcore.so* && \
    make install && \
    chmod 755 /usr/local/lib/libxvidcore.so && \
    rm -f /usr/local/lib/libxvidcore.a
fi

