#!/bin/bash

# Exit silently if CUDA is not installed.
[[ ! -f /usr/local/cuda/include/cuda.h ]] && exit 0

name=ffmpeg
branch=release/4.4
echo "building ${name} branch ${branch}"

mkdir -p builddir && cd builddir
rm -fr ${name}

if [[ ! -f ${name}.tar.gz ]]; then
    url="https://git.ffmpeg.org/ffmpeg.git"
    echo "git clone --depth 1 --branch ${branch} ${url}"
    git clone --depth 1 --branch ${branch} ${url}
    tar czf ${name}.tar.gz ${name}
else
    tar xzf ${name}.tar.gz
fi

if [[ -d ${name} ]]; then
    source ../../localenv # pick up $cudaarch and $cudacode
    if [[ -z ${cudaarch} ]]; then
        echo "Error: Variable 'cudaarch' is undefined in 'localenv'."
        exit 1
    fi
    if [[ -z ${cudacode} ]]; then
        echo "Error: Variable 'cudacode' is undefined in 'localenv'."
        exit 1
    fi

    # check /opt/nvidia/{lib64,lib} in the event installation inconsistent
    if [[ -f /opt/nvidia/lib64/libGL.so ]]; then
        ldflags="-Wl,-rpath=/usr/local/lib:/opt/nvidia/lib64:/usr/local/cuda/lib64 -flto -fuse-linker-plugin"
    else
        ldflags="-Wl,-rpath=/usr/local/lib:/opt/nvidia/lib:/usr/local/cuda/lib64 -flto -fuse-linker-plugin"
    fi

    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    export LD_LIBRARY_PATH=/usr/local/lib

    cores=`grep -c '^cpu[0-9]' /proc/stat`
    cd ${name}

    if [[ -f /opt/nvidia/bin/nvidia-settings ]]; then
        vdpau="--enable-vdpau"
    else
        vdpau=""
    fi

    ./configure \
        --prefix=/usr/local \
        --extra-cflags="-I/usr/local/include -I/usr/local/cuda/include" \
        --extra-ldflags="-L/usr/local/lib -L/opt/nvidia/lib64 -L/opt/nvidia/lib -L/usr/local/cuda/lib64 ${ldflags}" \
        --extra-libs="-lpthread -lm" --ar=gcc-ar \
        --enable-hardcoded-tables --arch=x86_64 --enable-x86asm \
        --disable-podpages --disable-static --enable-shared --enable-pthreads \
        --enable-avcodec --enable-bzlib --enable-gcrypt --enable-gmp \
        --enable-gnutls --enable-fontconfig --enable-libaom --enable-libass \
        --enable-libdav1d --enable-libdrm --enable-libfdk-aac \
        --enable-libfreetype --enable-libmfx --enable-libmp3lame \
        --enable-libopus --enable-libpulse --enable-librsvg --enable-libspeex \
        --enable-libsvtav1 --enable-libtheora --enable-libv4l2 \
        --enable-libvidstab --enable-libvmaf --enable-libvorbis \
        --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 \
        --enable-libxcb --enable-libxcb-shape --enable-libxcb-shm \
        --enable-libxcb-xfixes --enable-libxml2 --enable-libxvid \
        --enable-opengl --enable-postproc --enable-sdl2 --enable-vaapi $vdpau \
        --enable-zlib --enable-ffplay --enable-gpl --enable-nonfree \
        --enable-version3 --enable-cuda-nvcc --nvcc=/usr/local/cuda/bin/nvcc \
        --nvccflags="-gencode arch=${cudaarch},code=${cudacode} -O2 -m64 -ptx" \
        --enable-cuvid --enable-nvdec --enable-nvenc --enable-libnpp || exit $?

    # The libva-vdpau-driver always assumes the connection type "X11".
    if [[ -f /opt/nvidia/bin/nvidia-settings ]]; then
        sed -i 's/^#define HAVE_VAAPI_DRM 1/#define HAVE_VAAPI_DRM 0/' config.h
    fi

    make -j ${cores} && make install
fi

